/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'etf' : null } |
  { 'cash' : null } |
  { 'stock' : null } |
  { 'crypto' : null };
export interface Goal {
  'id' : bigint,
  'userId' : Principal,
  'name' : string,
  'deadline' : string,
  'targetAmount' : number,
  'currentAmount' : number,
}
export interface Holding {
  'id' : bigint,
  'currentPrice' : number,
  'ticker' : string,
  'userId' : Principal,
  'name' : string,
  'avgCost' : number,
  'quantity' : number,
  'category' : Category,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGoal' : ActorMethod<[string, number, number, string], bigint>,
  'addHolding' : ActorMethod<
    [string, string, Category, number, number, number],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerCategories' : ActorMethod<[], Array<Category>>,
  'getCallerGoals' : ActorMethod<[], Array<Goal>>,
  'getCallerHoldings' : ActorMethod<[], Array<Holding>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeGoal' : ActorMethod<[bigint], undefined>,
  'removeHolding' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedSampleData' : ActorMethod<[], undefined>,
  'updateGoal' : ActorMethod<
    [bigint, string, number, number, string],
    undefined
  >,
  'updateHolding' : ActorMethod<
    [bigint, string, string, Category, number, number, number],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];