/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'etf' : IDL.Null,
  'cash' : IDL.Null,
  'stock' : IDL.Null,
  'crypto' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Goal = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'deadline' : IDL.Text,
  'targetAmount' : IDL.Float64,
  'currentAmount' : IDL.Float64,
});
export const Holding = IDL.Record({
  'id' : IDL.Nat,
  'currentPrice' : IDL.Float64,
  'ticker' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'avgCost' : IDL.Float64,
  'quantity' : IDL.Float64,
  'category' : Category,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGoal' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addHolding' : IDL.Func(
      [IDL.Text, IDL.Text, Category, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getCallerGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getCallerHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeGoal' : IDL.Func([IDL.Nat], [], []),
  'removeHolding' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedSampleData' : IDL.Func([], [], []),
  'updateGoal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
      [],
      [],
    ),
  'updateHolding' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Float64,
        IDL.Float64,
        IDL.Float64,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'etf' : IDL.Null,
    'cash' : IDL.Null,
    'stock' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Goal = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'deadline' : IDL.Text,
    'targetAmount' : IDL.Float64,
    'currentAmount' : IDL.Float64,
  });
  const Holding = IDL.Record({
    'id' : IDL.Nat,
    'currentPrice' : IDL.Float64,
    'ticker' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'avgCost' : IDL.Float64,
    'quantity' : IDL.Float64,
    'category' : Category,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGoal' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addHolding' : IDL.Func(
        [IDL.Text, IDL.Text, Category, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getCallerGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getCallerHoldings' : IDL.Func([], [IDL.Vec(Holding)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeGoal' : IDL.Func([IDL.Nat], [], []),
    'removeHolding' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedSampleData' : IDL.Func([], [], []),
    'updateGoal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Float64, IDL.Text],
        [],
        [],
      ),
    'updateHolding' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };